"""phase2_schema

Revision ID: e6b3259c5c3b
Revises: b8943d660dc4
Create Date: 2026-06-08 23:37:06.047224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b3259c5c3b'
down_revision: Union[str, Sequence[str], None] = 'b8943d660dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sending_domains',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('warmup_day', sa.Integer(), nullable=False),
    sa.Column('send_count', sa.Integer(), nullable=False),
    sa.Column('bounce_count', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('paused_reason', sa.String(length=255), nullable=True),
    sa.Column('last_send_date', sa.Date(), nullable=True),
    sa.Column('emails_sent_today', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sending_domains_tenant_id'), 'sending_domains', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.add_column('outreach_emails', sa.Column('to_email', sa.String(length=255), nullable=True))
    op.add_column('outreach_emails', sa.Column('message_id', sa.String(length=255), nullable=True))
    op.add_column('outreach_emails', sa.Column('reply_intent', sa.String(length=50), nullable=True))
    op.add_column('outreach_emails', sa.Column('gmail_thread_id', sa.String(length=255), nullable=True))
    op.add_column('outreach_emails', sa.Column('follow_up_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outreach_emails', 'follow_up_count')
    op.drop_column('outreach_emails', 'gmail_thread_id')
    op.drop_column('outreach_emails', 'reply_intent')
    op.drop_column('outreach_emails', 'message_id')
    op.drop_column('outreach_emails', 'to_email')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sending_domains_tenant_id'), table_name='sending_domains')
    op.drop_table('sending_domains')
    # ### end Alembic commands ###
