import json

from groq import AsyncGroq
from typing_extensions import TypedDict

from langgraph.graph import END, StateGraph

from app.core.config import settings
from app.core.logging import logger
from app.models.brand_profile import BrandProfile
from app.tools.google_maps import get_place_details, search_places

# ---------------------------------------------------------------------------
# Chain blocklist (case-insensitive substring match)
# ---------------------------------------------------------------------------

CHAIN_NAMES: set[str] = {
    "sephora",
    "ulta",
    "cvs",
    "walgreens",
    "target",
    "walmart",
    "amazon",
    "nordstrom",
    "macy",
    "bloomingdale",
    "tj maxx",
    "marshalls",
    "ross",
    "bath & body",
    "victoria's secret",
}

# ---------------------------------------------------------------------------
# State
# ---------------------------------------------------------------------------


class ScoutState(TypedDict):
    brand_profile: BrandProfile
    vertical_tag: str
    target_location: str
    max_stores: int
    search_queries: list[str]        # generated by LLM
    raw_places: list[dict]           # from Google Maps
    enriched_stores: list[dict]      # with details added
    discovered_stores: list[dict]    # after filtering, as plain dicts
    errors: list[str]


# ---------------------------------------------------------------------------
# Node helpers
# ---------------------------------------------------------------------------

_QUERY_SYSTEM_PROMPT = """\
You are a retail discovery specialist. Generate search queries to find indie boutique stores \
that would be a great fit to carry a brand's products. The stores should match the brand's \
aesthetic and product categories.

Return a JSON object with exactly one key: "queries" — a list of 5 to 8 search query strings. \
Each query should be specific and mention the store type and location.

Examples:
  "aesthetic skincare boutique Brooklyn"
  "clean beauty salon NYC"
  "indie gift shop Park Slope"

Respond with ONLY valid JSON. No markdown fences, no explanation.
"""


def _is_chain(name: str) -> bool:
    """Return True if the store name contains a known chain identifier."""
    name_lower = name.lower()
    return any(chain in name_lower for chain in CHAIN_NAMES)


# ---------------------------------------------------------------------------
# Nodes
# ---------------------------------------------------------------------------


async def validate_inputs_node(state: ScoutState) -> dict:
    errors: list[str] = list(state.get("errors", []))

    if state.get("brand_profile") is None:
        errors.append("brand_profile is required and must not be None")

    location = state.get("target_location", "")
    if not location or not location.strip():
        errors.append("target_location is required and must not be empty")

    if errors:
        logger.warning("scout_validation_failed", errors=errors)
        return {
            "errors": errors,
            "search_queries": [],
            "raw_places": [],
            "enriched_stores": [],
            "discovered_stores": [],
        }

    return {"errors": errors}


async def generate_queries_node(state: ScoutState) -> dict:
    brand_profile: BrandProfile = state["brand_profile"]
    vertical_tag: str = state["vertical_tag"]
    target_location: str = state["target_location"]

    user_content = (
        f"Brand: {brand_profile.brand_name}\n"
        f"Vertical: {vertical_tag}\n"
        f"Aesthetic keywords: {', '.join(brand_profile.aesthetic_keywords)}\n"
        f"Product categories: {', '.join(brand_profile.product_categories)}\n"
        f"Target location: {target_location}\n\n"
        "Generate 5-8 search queries to find indie retail boutiques in this location "
        "that would be a great fit to carry this brand's products."
    )

    client = AsyncGroq(api_key=settings.groq_api_key)
    try:
        response = await client.chat.completions.create(
            model=settings.groq_model,
            messages=[
                {"role": "system", "content": _QUERY_SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
            response_format={"type": "json_object"},
            max_tokens=512,
            temperature=0.7,
        )
    except Exception as exc:
        logger.error("groq_query_generation_failed", error=str(exc))
        errors = list(state.get("errors", []))
        errors.append(f"LLM query generation failed: {exc}")
        return {"errors": errors, "search_queries": []}

    assert response.usage is not None
    token_usage = {
        "input_tokens": response.usage.prompt_tokens,
        "output_tokens": response.usage.completion_tokens,
    }
    logger.info(
        "groq_token_usage",
        node="generate_queries",
        model=settings.groq_model,
        input_tokens=token_usage["input_tokens"],
        output_tokens=token_usage["output_tokens"],
    )

    parsed: dict = json.loads(response.choices[0].message.content or "")
    queries: list[str] = parsed.get("queries", [])

    if not queries:
        logger.warning("generate_queries_empty_response", raw=parsed)
        errors = list(state.get("errors", []))
        errors.append("LLM returned no search queries")
        return {"errors": errors, "search_queries": []}

    logger.info("scout_queries_generated", count=len(queries), location=state["target_location"])
    return {"search_queries": queries}


async def search_maps_node(state: ScoutState) -> dict:
    queries: list[str] = state.get("search_queries", [])
    target_location: str = state["target_location"]
    max_stores: int = state.get("max_stores", 50)
    api_key: str = settings.google_maps_api_key

    seen_place_ids: set[str] = set()
    raw_places: list[dict] = []
    errors: list[str] = list(state.get("errors", []))

    for query in queries:
        if len(raw_places) >= max_stores:
            break
        try:
            results = await search_places(query, target_location, api_key)
        except Exception as exc:
            logger.error("search_places_failed", query=query, error=str(exc))
            errors.append(f"Google Maps search failed for query '{query}': {exc}")
            return {"raw_places": [], "errors": errors}

        for place in results:
            place_id = place.get("place_id", "")
            if not place_id or place_id in seen_place_ids:
                continue
            seen_place_ids.add(place_id)
            raw_places.append(place)
            if len(raw_places) >= max_stores:
                break

    logger.info("scout_maps_search_complete", unique_places=len(raw_places))
    return {"raw_places": raw_places, "errors": errors}


async def enrich_stores_node(state: ScoutState) -> dict:
    raw_places: list[dict] = state.get("raw_places", [])
    max_stores: int = state.get("max_stores", 50)
    api_key: str = settings.google_maps_api_key

    enriched_stores: list[dict] = []

    for place in raw_places[:max_stores]:
        place_id = place.get("place_id", "")
        merged = dict(place)

        if place_id:
            try:
                details = await get_place_details(place_id, api_key)
                merged.update(details)
            except Exception as exc:
                logger.warning(
                    "enrich_store_failed",
                    place_id=place_id,
                    name=place.get("name", ""),
                    error=str(exc),
                )
                # Skip enrichment but still keep the base place data
        else:
            logger.warning("enrich_store_no_place_id", name=place.get("name", ""))

        enriched_stores.append(merged)

    logger.info("scout_enrich_complete", enriched_count=len(enriched_stores))
    return {"enriched_stores": enriched_stores}


async def filter_stores_node(state: ScoutState) -> dict:
    enriched_stores: list[dict] = state.get("enriched_stores", [])
    filtered: list[dict] = []

    for store in enriched_stores:
        name: str = store.get("name", "")

        # Remove chains
        if _is_chain(name):
            logger.info("scout_chain_filtered", name=name)
            continue

        # Keep only operational stores (or those without status set)
        business_status = store.get("business_status", "")
        if business_status and business_status != "OPERATIONAL":
            logger.info("scout_non_operational_filtered", name=name, status=business_status)
            continue

        # Compute vibe_score from rating
        rating = store.get("rating")
        vibe_score: float = (float(rating) / 5.0) * 10.0 if rating is not None else 0.0
        store["vibe_score"] = round(vibe_score, 2)

        filtered.append(store)

    logger.info("scout_filter_complete", kept=len(filtered), removed=len(enriched_stores) - len(filtered))
    return {"enriched_stores": filtered}


async def build_candidates_node(state: ScoutState) -> dict:
    enriched_stores: list[dict] = state.get("enriched_stores", [])
    discovered_stores: list[dict] = []

    for store in enriched_stores:
        candidate: dict = {
            "name": store.get("name", ""),
            "address": store.get("formatted_address", ""),
            "google_place_id": store.get("place_id", ""),
            "instagram_handle": store.get("instagram_handle", ""),
            "vibe_score": store.get("vibe_score", 0.0),
            "lead_score": 0.0,
            "status": "new",
        }
        discovered_stores.append(candidate)

    logger.info("scout_candidates_built", count=len(discovered_stores))
    return {"discovered_stores": discovered_stores}


# ---------------------------------------------------------------------------
# Routing
# ---------------------------------------------------------------------------


def route_after_validate(state: ScoutState) -> str:
    if state.get("errors"):
        return END
    return "generate_queries"


def route_after_search(state: ScoutState) -> str:
    if not state.get("raw_places"):
        logger.warning("scout_no_places_found", location=state.get("target_location"))
        return END
    return "enrich_stores"


# ---------------------------------------------------------------------------
# Graph
# ---------------------------------------------------------------------------


def _build_graph() -> StateGraph:
    graph = StateGraph(ScoutState)

    graph.add_node("validate_inputs", validate_inputs_node)
    graph.add_node("generate_queries", generate_queries_node)
    graph.add_node("search_maps", search_maps_node)
    graph.add_node("enrich_stores", enrich_stores_node)
    graph.add_node("filter_stores", filter_stores_node)
    graph.add_node("build_candidates", build_candidates_node)

    graph.set_entry_point("validate_inputs")

    graph.add_conditional_edges("validate_inputs", route_after_validate)
    graph.add_edge("generate_queries", "search_maps")
    graph.add_conditional_edges("search_maps", route_after_search)
    graph.add_edge("enrich_stores", "filter_stores")
    graph.add_edge("filter_stores", "build_candidates")
    graph.add_edge("build_candidates", END)

    return graph


scout_graph = _build_graph().compile()
